### ISSUE TITLE
Crash releasing write lock with outstanding read lockers

### ISSUE THREAD

**Issue by timclassic** [uwiger/locks#15]
I was playing with `locks` to see if I could use it to help me synchronize shutdown of a process that may have in-flight new requests.  On a single node I started three lock agents.  I first took out a write lock with one, and then requested read locks with the other two, and they blocked (as expected).

Then, I ended the transaction for the agent that had the write lock with `end_transaction/1`, and both of the blocking read locks crashed.

To replicate, I added the following test to `locks_tests.erl`, added it to `run_test_/0`, and ran it:
``` erlang
one_lock_wrr_clients() ->
    L = [?MODULE, ?LINE],
    script([1,2,3],
           [{1, ?LINE, locks, lock, ['$agent', L, write], match({ok,[]})},
            {2, ?LINE, locks, lock_nowait, ['$agent', L, read], match(ok)},
            {3, ?LINE, locks, lock_nowait, ['$agent', L, read], match(ok)},
            {1, ?LINE, locks, end_transaction, ['$agent'], match(ok)},
            {2, ?LINE, locks, await_all_locks, ['$agent'],
             match({have_all_locks, []})},
            {3, ?LINE, locks, await_all_locks, ['$agent'],
             match({have_all_locks, []})}
           ]).
```
I am not confident that I should see `{have_all_locks, []}` for both calls to `await_all_locks/1`, but that doesn't really matter, because I get the following crash:
```
=ERROR REPORT==== 16-Oct-2015::01:14:18 ===
    locks_agent: aborted
    reason: function_clause
    trace: [{locks_agent,lock_holder,
                         [[{w,[{entry,<0.81.0>,<0.80.0>,3,direct},
                               {entry,<0.79.0>,<0.78.0>,2,direct}]}]],
                         [{file,"src/locks_agent.erl"},{line,1080}]},
            {locks_agent,'-pp_locks/1-lc$^0/1-0-',1,
                         [{file,"src/locks_agent.erl"},{line,1077}]},
            {locks_agent,all_locks_status,1,
                         [{file,"src/locks_agent.erl"},{line,1068}]},
            {locks_agent,check_if_done,2,
                         [{file,"src/locks_agent.erl"},{line,933}]},
            {locks_agent,handle_call,3,
                         [{file,"src/locks_agent.erl"},{line,509}]},
            {locks_agent,handle_msg,2,
                         [{file,"src/locks_agent.erl"},{line,266}]},
            {locks_agent,loop,1,[{file,"src/locks_agent.erl"},{line,261}]},
            {locks_agent,agent_init,3,
                         [{file,"src/locks_agent.erl"},{line,228}]}]
ERROR: {mismatch,
           [exit,
            {{function_clause,
                 [{locks_agent,agent_init,3,
                      [{file,"src/locks_agent.erl"},{line,235}]}]},
             {gen_server,call,[<0.79.0>,await_all_locks,infinity]}},
            normal,[]]}
```
Even though this crash was created with a lock_nowait/await_all_locks pair,  it is exactly the same crash I received in my original testing.

The analysis I have done so far makes me think this is related to lock upgrades from read to write.  Are lock upgrades supposed to happen automatically?  Am I fundamentally misunderstanding the API?  I don't know yet if this crash occurs if each agent is on a different node.

**Comment by timclassic** [comment]
I have submitted a PR with the test changes for easy reproduction.

**Comment by uwiger** [comment]
Thanks. I believe the above PR solves the problem (the test suite, including your test, passes). Could you take a look?

**Comment by timclassic** [comment]
A local eunit run looks good.  I also ran through the interactive test cases that originally demonstrated the bug, and everything behaved as expected.

Thank you for the quick turnaround!

**Comment by uwiger** [comment]
Ok then, I've merged it into master. Thank you so much for your help!
