### ISSUE TITLE
ask_candidates/2 never demonitors

### ISSUE THREAD

**Issue by bullno1** [uwiger/locks#2]
Every time ask_candidates/2 is called, it monitors all candidates: https://github.com/uwiger/locks/blob/master/src/locks_leader.erl#L238

However, it never demonitors and duplicated or unexpected 'DOWN' messages may happen. 

Spawning a middle-man process like how gen_server:multi_call does it or demonitor in collect_replies/1 can solve this problem.

**Comment by uwiger** [comment]
Closing. If this is still a problem, please create a new issue.
