### ISSUE TITLE
Application bound to a deprecated edown version

### ISSUE THREAD

**Issue by kzemek** [uwiger/locks#27]
`locks` pulls in `plain_fsm` which in turn pulls in `esl/edown`, which doesn't compile under new Erlang versions as per https://github.com/esl/edown/issues/32 . The script in `priv/check_edown.script` doesn't remove this dependency under current rebar and rebar3.

**Comment by benoitc** [comment]
this has been fixed in latest release

**Comment by uwiger** [comment]
Yes, closing this issue.
